### ISSUE TITLE
Multiplayer game

### ISSUE THREAD

**Issue by Janekk** [fbsamples/web-friend-smash-v2#8]
Hi,

Thanks for the comprehensive tutorial. I have a question though, does this repo cover also a multiplayer game scenario? Let's say I want to build a turn-based game for two players. Do I have to use some additional API for that, besides what has been presented in this sample? 

Or do you have any tutorial showing how to implement a multiplayer game?

**Comment by connortreacy** [comment]
Hi, thanks for the feedback. 

We don't have a dedicated turn-based tutorial. You won't need any additional APIs to achieve a multiplayer game scenario, but there are some things that will help. For starters, make sure you're using [Frictionless Requests](https://developers.facebook.com/docs/games/requests/v2.2#frictionless-requests) and [Structured Requests](https://developers.facebook.com/docs/games/requests/v2.2#sendexperience) for sending turn-based Requests.

Hope this helps!
